# Generated by Django 4.0.6 on 2022-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_slug_shop_slug_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AddField(
            model_name='book',
            name='slug_author',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_isbn',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_publication',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_title',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug_name',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug_town',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
    ]
