# Generated by Django 4.0.6 on 2022-08-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_book_slug_remove_shop_slug_book_slug_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug_author',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_isbn',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_publication',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_title',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug_name',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug_town',
            field=models.SlugField(null=True),
        ),
    ]
