# Generated by Django 4.0.6 on 2022-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_slug_author_alter_book_slug_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='town',
            field=models.SlugField(),
        ),
    ]
