# Generated by Django 4.0.6 on 2022-08-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_shop_name_alter_shop_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug_town',
        ),
    ]
