# Generated by Django 4.0.6 on 2022-08-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_book_slug_author_remove_book_slug_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='bookstore_name',
        ),
    ]
