# Generated by Django 4.0.6 on 2022-08-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_book_author_alter_book_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
