# Generated by Django 4.0.6 on 2022-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.SlugField(),
        ),
    ]
