# Generated by Django 4.0.6 on 2022-08-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_slug_author_alter_book_slug_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug_author',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_isbn',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_publication',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug_title',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug_name',
            field=models.SlugField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug_town',
            field=models.SlugField(default='', null=True),
        ),
    ]
